### ISSUE TITLE
[Feature]: maybe... all of us are struggling because the problems we had................... maybe add a modpack? please?

### ISSUE THREAD

**Issue by abu786786** [TaintedBlock/crackers-wither-storm-plus#28]
**Describe feature you'd like to be added**
more infracted blocks and items

**Comment by abu786786** [comment]
its been 2 night i was struggling, we realy need it... a modpack. please?

**Comment by abu786786** [comment]
its been 2 night i was struggling, we realy need it... a modpack. please?

**Comment by abu786786** [comment]
its been 2 night i was struggling, we really need it... a modpack. please?

**Comment by TaintedBlock** [comment]
Going to assume you mean infected stuff. I'll add them to my own discretion. As of now, I have no intent on adding more items as I feel like what is available is fine for now. As for blocks, I'm not doing those simply because blocks cannot be made by normal means and would overall just not be useful or good performance wise.
